version: '3.8'

services:
  backend:
    build:
      context: ../greenhouse-backend-cloud
      dockerfile: Dockerfile
    ports:
      - "7128:7128"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7128
    volumes:
      - ../greenhouse-backend-cloud/EfcDataAccess/Greenhouse.db:/app/EfcDataAccess/Greenhouse.db

  frontend:
    build:
      context: ../green-house-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:7128
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ../green-house-dashboard/src:/usr/src/app/src  # Maps the source directory
      - /usr/src/app/node_modules

networks:
  default:
    driver: bridge
